export const ANALYTICS_REPORT_DEFAULT_LIMIT =
    25;

export const ANALYTICS_REPORT_MAX_LIMIT =
    100;

export const ANALYTICS_EXPORT_MAX_ROWS =
    5_000;

export const ANALYTICS_EXPORT_MAX_DAYS =
    90;

export const ANALYTICS_SEARCH_MAX_LENGTH =
    100;